name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.6'
    - run: sudo apt-get -y update
    - run: sudo apt-get -y install libgmp-dev libmpc-dev libmpfr-dev
    - run: pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: pip install -r web_console_v2/api/requirements.txt
    - run: bash ./ci/ci_test.sh