name: Tufuwu/test2
on:
  push:
    branches:
    - "**/*"
  pull_request:

jobs:
  test:
    runs-on: # this agent type is not supported: [[{"dist"=>"Xenial"}]]
             ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.6'
    - run: cd ~/
    - run: wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
    - run: python3 litex_setup.py init install --user
    - run: cd ${{ github.workspace }}
    - run: python3 setup.py install --user
    - run: cd ${{ github.workspace }}
    - run: python setup.py test